title: [Lucas Meira Rolo]
description: I am a software engineering student, and this portfolio showcases a selection of my projects, highlighting my skills and expertise in the field of informatics. 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
